package com.lele.entity;

public enum Action {
	LOGIN, HALL, GAME_CREATE_ROOM, GAME_JOIN_ROOM, GAME_WAIT, GAME_NEW_ROUND_START, GAME_INIT, GAME_PUT_CART, GAME_MEET, CHAT, GAME_WIN, GAME_WAIT_FOR_NEXT_ROUND, LIVE, ERROR

}
